
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABRE_CHAVE ABRE_PARENTESE AND BOOL DESLIGAR DISPOSITIVO_KW ENTAO ENVIAR_ALERTA FECHA_CHAVE FECHA_PARENTESE IGUAL LIGAR MSG NAMEDEVICE NUM OBSERVATION OPLOGIC PARA_TODOS PONTO SE SENAO SET VERIFICAR VIRGULAprogram : devices cmdsdevices : device devicesdevices : deviceid_any : NAMEDEVICE\n| OBSERVATIONdevice : DISPOSITIVO_KW ABRE_CHAVE NAMEDEVICE FECHA_CHAVEdevice : DISPOSITIVO_KW ABRE_CHAVE NAMEDEVICE VIRGULA id_any FECHA_CHAVEcmds : cmd PONTO cmdscmds : cmd PONTOcmd : attrib\n| obsact\n| actattrib : SET id_any IGUAL varattrib : SET id_any IGUAL actexecutevar : NUM\n| BOOL\n| NAMEDEVICE\n| OBSERVATIONobsact : SE obs ENTAO cmdsobsact : SE obs ENTAO cmds SENAO cmdsobs : id_any OPLOGIC varobs : id_any OPLOGIC var AND obsact : ACTION NAMEDEVICE\n| actalertactexecute : VERIFICAR ABRE_PARENTESE NAMEDEVICE FECHA_PARENTESEACTION : LIGAR\n| DESLIGARactalert : ENVIAR_ALERTA ABRE_PARENTESE MSG FECHA_PARENTESE NAMEDEVICEactalert : ENVIAR_ALERTA ABRE_PARENTESE MSG VIRGULA id_any FECHA_PARENTESE NAMEDEVICEactalert : ENVIAR_ALERTA ABRE_PARENTESE MSG FECHA_PARENTESE PARA_TODOS devicelistactalert : ENVIAR_ALERTA ABRE_PARENTESE MSG VIRGULA id_any FECHA_PARENTESE PARA_TODOS devicelistdevicelist : NAMEDEVICE VIRGULA devicelistdevicelist : NAMEDEVICE'
    
_lr_action_items = {'DISPOSITIVO_KW':([0,3,33,53,],[4,4,-6,-7,]),'$end':([1,5,19,28,],[0,-1,-9,-8,]),'SET':([2,3,17,19,30,33,48,53,],[10,-3,-2,10,10,-6,10,-7,]),'SE':([2,3,17,19,30,33,48,53,],[11,-3,-2,11,11,-6,11,-7,]),'LIGAR':([2,3,17,19,30,33,48,53,],[14,-3,-2,14,14,-6,14,-7,]),'DESLIGAR':([2,3,17,19,30,33,48,53,],[15,-3,-2,15,15,-6,15,-7,]),'ENVIAR_ALERTA':([2,3,17,19,30,33,48,53,],[16,-3,-2,16,16,-6,16,-7,]),'ABRE_CHAVE':([4,],[18,]),'PONTO':([6,7,8,9,13,19,25,28,35,36,37,38,39,40,42,50,55,57,58,60,62,64,65,],[19,-10,-11,-12,-24,-9,-23,-8,-13,-14,-15,-16,-17,-18,-19,-28,-20,-30,-33,-25,-29,-32,-31,]),'NAMEDEVICE':([10,11,12,14,15,18,29,31,34,44,45,47,49,51,59,61,63,],[21,21,25,-26,-27,27,39,39,21,50,21,54,21,58,62,58,58,]),'OBSERVATION':([10,11,29,31,34,45,49,],[22,22,40,40,22,22,22,]),'ABRE_PARENTESE':([16,41,],[26,47,]),'SENAO':([19,28,42,],[-9,-8,48,]),'IGUAL':([20,21,22,],[29,-4,-5,]),'OPLOGIC':([21,22,24,],[-4,-5,31,]),'FECHA_CHAVE':([21,22,27,46,],[-4,-5,33,53,]),'FECHA_PARENTESE':([21,22,32,52,54,],[-4,-5,44,59,60,]),'ENTAO':([23,37,38,39,40,43,56,],[30,-15,-16,-17,-18,-21,-22,]),'MSG':([26,],[32,]),'VIRGULA':([27,32,58,],[34,45,61,]),'NUM':([29,31,],[37,37,]),'BOOL':([29,31,],[38,38,]),'VERIFICAR':([29,],[41,]),'AND':([37,38,39,40,43,],[-15,-16,-17,-18,49,]),'PARA_TODOS':([44,59,],[51,63,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'devices':([0,3,],[2,17,]),'device':([0,3,],[3,3,]),'cmds':([2,19,30,48,],[5,28,42,55,]),'cmd':([2,19,30,48,],[6,6,6,6,]),'attrib':([2,19,30,48,],[7,7,7,7,]),'obsact':([2,19,30,48,],[8,8,8,8,]),'act':([2,19,30,48,],[9,9,9,9,]),'ACTION':([2,19,30,48,],[12,12,12,12,]),'actalert':([2,19,30,48,],[13,13,13,13,]),'id_any':([10,11,34,45,49,],[20,24,46,52,24,]),'obs':([11,49,],[23,56,]),'var':([29,31,],[35,43,]),'actexecute':([29,],[36,]),'devicelist':([51,61,63,],[57,64,65,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> devices cmds','program',2,'p_program','parser.py',7),
  ('devices -> device devices','devices',2,'p_devices_multiple','parser.py',12),
  ('devices -> device','devices',1,'p_devices_single','parser.py',16),
  ('id_any -> NAMEDEVICE','id_any',1,'p_id_any','parser.py',21),
  ('id_any -> OBSERVATION','id_any',1,'p_id_any','parser.py',22),
  ('device -> DISPOSITIVO_KW ABRE_CHAVE NAMEDEVICE FECHA_CHAVE','device',4,'p_device_simple','parser.py',27),
  ('device -> DISPOSITIVO_KW ABRE_CHAVE NAMEDEVICE VIRGULA id_any FECHA_CHAVE','device',6,'p_device_complete','parser.py',33),
  ('cmds -> cmd PONTO cmds','cmds',3,'p_cmds_multiple','parser.py',40),
  ('cmds -> cmd PONTO','cmds',2,'p_cmds_single','parser.py',44),
  ('cmd -> attrib','cmd',1,'p_cmd','parser.py',49),
  ('cmd -> obsact','cmd',1,'p_cmd','parser.py',50),
  ('cmd -> act','cmd',1,'p_cmd','parser.py',51),
  ('attrib -> SET id_any IGUAL var','attrib',4,'p_attrib_var','parser.py',56),
  ('attrib -> SET id_any IGUAL actexecute','attrib',4,'p_attrib_execute','parser.py',61),
  ('var -> NUM','var',1,'p_var','parser.py',66),
  ('var -> BOOL','var',1,'p_var','parser.py',67),
  ('var -> NAMEDEVICE','var',1,'p_var','parser.py',68),
  ('var -> OBSERVATION','var',1,'p_var','parser.py',69),
  ('obsact -> SE obs ENTAO cmds','obsact',4,'p_obsact_simple','parser.py',74),
  ('obsact -> SE obs ENTAO cmds SENAO cmds','obsact',6,'p_obsact_complete','parser.py',80),
  ('obs -> id_any OPLOGIC var','obs',3,'p_obs_simple','parser.py',87),
  ('obs -> id_any OPLOGIC var AND obs','obs',5,'p_obs_compound','parser.py',92),
  ('act -> ACTION NAMEDEVICE','act',2,'p_act','parser.py',97),
  ('act -> actalert','act',1,'p_act','parser.py',98),
  ('actexecute -> VERIFICAR ABRE_PARENTESE NAMEDEVICE FECHA_PARENTESE','actexecute',4,'p_actexecute','parser.py',106),
  ('ACTION -> LIGAR','ACTION',1,'p_action','parser.py',111),
  ('ACTION -> DESLIGAR','ACTION',1,'p_action','parser.py',112),
  ('actalert -> ENVIAR_ALERTA ABRE_PARENTESE MSG FECHA_PARENTESE NAMEDEVICE','actalert',5,'p_actalert_simple','parser.py',119),
  ('actalert -> ENVIAR_ALERTA ABRE_PARENTESE MSG VIRGULA id_any FECHA_PARENTESE NAMEDEVICE','actalert',7,'p_actalert_var','parser.py',124),
  ('actalert -> ENVIAR_ALERTA ABRE_PARENTESE MSG FECHA_PARENTESE PARA_TODOS devicelist','actalert',6,'p_actalert_broadcast_simple','parser.py',129),
  ('actalert -> ENVIAR_ALERTA ABRE_PARENTESE MSG VIRGULA id_any FECHA_PARENTESE PARA_TODOS devicelist','actalert',8,'p_actalert_broadcast_var','parser.py',134),
  ('devicelist -> NAMEDEVICE VIRGULA devicelist','devicelist',3,'p_devicelist_multiple','parser.py',140),
  ('devicelist -> NAMEDEVICE','devicelist',1,'p_devicelist_single','parser.py',144),
]
